First stab at github actions integration
I also made it work with macports as well as brew.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -48,34 +48,33 @@ construct_configure_options() {
   echo "$configure_options"
 }
 
-
-homebrew_package_path() {
+darwin_package_path() {
   local package_name=$1
 
   if [ "$(brew ls --versions $package_name)" = "" ]; then
-    echo ""
+    echo "/opt/local/lib"
   else
     echo "$(brew --prefix $package_name)"
   fi
 }
 
-
-exit_if_homebrew_not_installed() {
+exit_if_darwin_package_manager_not_installed() {
   if [ "$(brew --version 2>/dev/null)" = "" ]; then
-    echo "ERROR: Please install homebrew for OSX"
-    exit 1
+    if [ "$(port version 2>/dev/null)" = "" ]; then
+      echo "ERROR: Please install homebrew or macports for OSX"
+      exit 1
+    fi
   fi
 }
-
 
 os_based_configure_options() {
   local operating_system=$(uname -a)
   local configure_options=""
 
   if [[ "$operating_system" =~ "Darwin" ]]; then
-    exit_if_homebrew_not_installed
-    local openssl_path=$(homebrew_package_path openssl)
-    local pcre_path=$(homebrew_package_path pcre)
+    exit_if_darwin_package_manager_not_installed
+    local openssl_path=$(darwin_package_path openssl)
+    local pcre_path=$(darwin_package_path pcre)
   else
     local openssl_path=/usr
     local pcre_path=/usr
